name: Python CI

on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    
    permissions:
      contents: read
      actions: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
    
    - name: Run tests with coverage
      run: |
        pytest --maxfail=1 --disable-warnings --cov=. --cov-report=xml --cov-report=term
    
    - name: Debug coverage file generation
      run: ls -al && cat coverage.xml || echo "coverage.xml not found during debug!"
    
    - name: Verify coverage file exists
      run: |
        if [ ! -f coverage.xml ]; then
          echo "Error: coverage.xml not found!"
          exit 1
        fi
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report-${{ matrix.python-version }}
        path: coverage.xml
